In [1]:
import pandas as pd
import numpy as np 

Exercise 1 : Maximum Value Replacement In Matrix

Create a random 5x5 matrix and replace the maximum value by 0.

In [5]:
import numpy as np

# Create a random 5x5 matrix
matrix = np.random.randint(1,100,size=(5,5))
print("Original matrix:")
print(matrix)
max_value = np.max(matrix)
print(f'Max:{max_value}')
matrix[matrix == max_value] = 0
print("\nMatrix after replacing the maximum value with 0:")
print(matrix)

Original matrix:
[[82 55 68 20 47]
 [43 53 87 39 41]
 [18 38 64 98 31]
 [56 67 10 19 68]
 [53 71 30 56 61]]
Max:98

Matrix after replacing the maximum value with 0:
[[82 55 68 20 47]
 [43 53 87 39 41]
 [18 38 64  0 31]
 [56 67 10 19 68]
 [53 71 30 56 61]]


Exercise 2 : Finding Common Values In Arrays

Find the common values between two random arrays of size 5.

In [10]:
matrix1 = np.random.randint(1,100,size=(5,5))
matrix2 = np.random.randint(1,100,size=(5,5))
print(f'Matrix 1 : {matrix1}\n')
print(f'Matrix 2 : {matrix2}\n')
common_values = matrix1[matrix1==matrix2]
print(common_values)

Matrix 1 : [[52  5 27 14 44]
 [64 38 22 76 49]
 [72 16 63 18 85]
 [56 12 11 65 84]
 [37 15 89 72 70]]

Matrix 2 : [[16 90 63 86 16]
 [95 82 19  6  7]
 [57 79 56 89 53]
 [82 12  2 85 93]
 [15 71 18 10 41]]

[12]


Exercise 3 : Sorting Array In Ascending And Descending Order

Create a random 1D array of size 10 and sort it in ascending and then in descending order.

In [11]:
array_10 = np.random.randint(1,100,size=(10))
array_10

array([63, 56, 43, 42, 63, 62, 34, 61, 71, 64])

In [13]:
ascending = np.sort(array_10)
descending = ascending[::-1]

print(f'Ascending: {ascending}')
print(f'Descending: {descending}')

Ascending: [34 42 43 56 61 62 63 63 64 71]
Descending: [71 64 63 63 62 61 56 43 42 34]


Exercise 4 : Matrix Rank Determination
Instructions
Generate a random 4x4 matrix and find the rank of the matrix.

In [14]:
array_4x4 = np.random.randint(1,100,size=(4,4))

In [16]:
rank = np.linalg.matrix_rank(array_4x4)

print("Rank of the Matrix:", rank)

Rank of the Matrix: 4


Exercise 5 : Creating Border Array

Create a 2D array with 1 on the border and 0 inside.

In [24]:
array = np.array([0 for _ in range(25)]).reshape(5,5)
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
array[0] = 1
array[-1] = 1
array[:,0] = 1
array[:,-1] = 1

In [26]:
array


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [27]:
array = np.ones((5, 5))

# Fill the inside of the array with 0s
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
