In [1]:
import numpy as np

Exercise 1 : Array Creation And Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

In [3]:
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2 : Type Conversion And Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [6]:
lst = [3.14, 2.17, 0, 1, 2]
array = np.array(lst, dtype=int)

Exercise 3 : Working With Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [7]:
array3d = np.arange(1,10).reshape(3,3)

In [8]:
array3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [9]:
array_2d = np.random.randint(0,100,size=(4,5))
array_2d

array([[72, 59, 66, 48, 81],
       [26, 34, 19, 12, 46],
       [ 1, 25, 41, 90, 49],
       [81, 55, 11, 24, 34]])

 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [14]:
array = np.array([20, 21, 22, 23, 24])
array[1]

21

In [17]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1, :]

array([20, 21, 22, 23, 24])

Exercise 6 : Reversing Elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [19]:
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
array[::-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

In [20]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sum_array = np.sum(arr)
average_array = np.mean(arr)

print("Sum:", sum_array, ", Average:", average_array)

Sum: 55 , Average: 5.5


Exercise 9 : Create Array And Change Its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [23]:
array_4x5 = np.arange(1,21).reshape(4,5)
array_4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercise 10 : Conditional Selection Of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_num = arr[arr%2 != 0]
odd_num

array([1, 3, 5, 7, 9])