In [1]:
import pandas as pd
import numpy as np 

Exercise 1 : Minimum And Maximum Of Random Array


Instructions


Create a 5x5 array with random values and find the minimum and maximum values.

In [16]:
array = np.random.rand(5, 5)

min_value = np.min(array)
max_value = np.max(array)

print(f'Min value: {min_value}')
print(f'Max value: {max_value}')
print(f"Min: {min_value:.2f}, Max: {max_value:.2f}")

Min value: 0.03685555747378866
Max value: 0.9633407734385429
Min: 0.04, Max: 0.96


Exercise 2 : Matrix Normalization

Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).

In [18]:
matrix = np.random.rand(3, 3)

mean = np.mean(matrix)
std_dev = np.std(matrix)

normalized_matrix = (matrix - mean) / std_dev

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.99552098 0.72336216 0.14438112]
 [0.55155086 0.85219696 0.81800884]
 [0.40753436 0.87060657 0.64179001]]

Normalized Matrix:
[[ 1.31138004  0.22426709 -2.08841853]
 [-0.46201706  0.73888567  0.60232442]
 [-1.03727752  0.81242111 -0.10156521]]


Exercise 3 : Evenly Spaced Elements In Array
Instructions
Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.

In [21]:
array = np.linspace(0, 10, num=50, endpoint=False)
array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

Exercise 4 : Matrix Multiplication
Instructions
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [28]:
array_5x3 = np.arange(1, 16).reshape(5, 3)
array_3x2 = np.arange(1, 7).reshape(3, 2)
product_matrx = np.dot(array_5x3,array_3x2)
product_matrx

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [29]:
array_5x3 = np.random.randint(1, 100, size=(5, 3))
array_3x2 = np.random.randint(1, 100, size=(3, 2))

product_matrix = np.dot(array_5x3, array_3x2)

print("Matrix A (5x3):")
print(array_5x3)
print("\nMatrix B (3x2):")
print(array_3x2)
print("\nResult of Matrix A multiplied by Matrix B:")
print(product_matrix)

Matrix A (5x3):
[[ 5 25 64]
 [83  6 17]
 [82 22 35]
 [14 11 47]
 [43 40  3]]

Matrix B (3x2):
[[45 25]
 [16 63]
 [41 99]]

Result of Matrix A multiplied by Matrix B:
[[3249 8036]
 [4528 4136]
 [5477 6901]
 [2733 5696]
 [2698 3892]]


In [30]:
array_5x3 = np.random.randint(1, 100, size=(5, 3))
array_3x2 = np.random.randint(1, 100, size=(3, 2))

product_matrix = array_5x3@array_3x2

print("Matrix A (5x3):")
print(array_5x3)
print("\nMatrix B (3x2):")
print(array_3x2)
print("\nResult of Matrix A multiplied by Matrix B:")
print(product_matrix)

Matrix A (5x3):
[[28 71 72]
 [46 41 29]
 [44 89 35]
 [87 43 85]
 [86 57 98]]

Matrix B (3x2):
[[72 17]
 [24  3]
 [90 69]]

Result of Matrix A multiplied by Matrix B:
[[10200  5657]
 [ 6906  2906]
 [ 8454  3430]
 [14946  7473]
 [16380  8395]]


Exercise 5

In [35]:
valid = np.random.randint(1,10)
araay1 = np.random.randint(1,100,size=(np.random.randint(1,10),valid))
array2 = np.random.randint(1,100,size=(valid,np.random.randint(1,10)))
result = araay1@array2

print(f"Matrix 1:")
print(araay1)
print("\nMatrix 2:")
print(array2)
print("\nResult of Matrix 1 multiplied by Matrix 2:")
print(result)

Matrix 1:
[[70 73 80 57 25 40 22]
 [56 32 94 51 90 42 88]
 [80 86  7 87 71 12 67]
 [94 91 23 31 53 83 30]
 [88  5 84 61 69 40 50]
 [ 4  9 32 26 92 82 29]
 [53 15 17 76 53 85 14]]

Matrix 2:
[[83 72]
 [80 48]
 [31  9]
 [67 10]
 [90 59]
 [ 5  1]
 [91  7]]

Result of Matrix 1 multiplied by Matrix 2:
[[22401 11503]
 [29857 12892]
 [32113 15491]
 [25787 15073]
 [25355 12403]
 [15115  6981]
 [17687  8759]]
